<?php

/**
 * @file
 * Provides rule-based advanced routing of SMS.
 */

use Drupal\sms_rule_based\Plugin\SmsRoutingRulePluginBase;

/**
 * Implements hook_theme().
 */
function sms_rule_based_theme() {
  $items['sms_rule_based_routing_rules'] = array(
    'variables' => array('ruleset' => NULL),
  );
  return $items;
}

/**
 * Preprocess function for sms_rule_based_routing_rule theme.
 */
function sms_rule_based_preprocess_sms_rule_based_routing_rules(&$variables) {
  $variables['long_ops'] = SmsRoutingRulePluginBase::getLongOperatorTypes();
}
