<?php

/**
 * @file
 * Provides advanced bulk sms site management functionality.
 */

include 'sms_advanced.queue.inc';
include 'sms_advanced.sender_id_block.inc';

use Drupal\sms\Message\SmsMessageInterface;
use Drupal\sms_advanced\AdvancedSmsRouting;
use Drupal\sms_advanced\Plugin\SmsRoutingRulePluginBase;

/**
 * Implements hook_theme().
 */
function sms_advanced_theme($existing, $type, $theme, $path) {
  $items['sms_advanced_routing_rules'] = array(
    'variables' => array('ruleset' => NULL),
  );

  return $items;
}

/**
 * Pre-process function for sms_advanced_routing_rule.
 */
function sms_advanced_preprocess_sms_advanced_routing_rules(&$variables) {
  $variables['long_ops'] = SmsRoutingRulePluginBase::getLongOperatorTypes();
}

/**
 * Sends SMS through SMS Framework.
 *
 * This function invokes preprocess and postprocess hooks prior to dispatching.
 *
 * If any of the preprocess hooks returns FALSE, sending will be aborted, and
 *   the postprocess hooks will not be called. This is designed to allow other
 *   modules to abort or postpone sending. E.g. this hook is used to implement
 *   scheduled / delayed sending and to prevent sending if credit is inadequate.
 *
 * hooks:
 *   hook_preprocess_sms_ui_send(&$sms, &$options)
 * 	 hook_postprocess_sms_ui_send(&$sms, &$options)
 *   post-process hooks will be invoked by _sms_advanced_process_send()
 *
 *
 * @param \Drupal\sms\Message\SmsMessageInterface $sms
 *   The SMS message value object.
 * @param array $options
 *   Additional options not specifically associated with the message.
 * 		- cron: specifies that this is a cron job call some modules may need this
 * 				information to determine how to behave
 * 		- queue: specifies that this batch should be queued for send irrespective
 * 				of other settings or number of recipients.
 *
 * @return \Drupal\sms\Message\SmsMessageResultInterface
 *   An object encapsulating the result of the SMS sending operation.
 *
 * @todo Need to decide if tokenization should take place here or before.
 * @todo Recipient number sanitization should be done separately (provide helper
 * 	function for that)
 */
function sms_advanced_send(SmsMessageInterface $sms, $options = array()) {
  \Drupal::service('sms_provider.advanced')->send($sms, $options);
}

/**
 * Dispatches the SMS message using the configured routing algorithm.
 *
 * @param \Drupal\sms\Message\SmsMessageInterface $sms
 *   The SMS message value object.
 *
 * @param array $options
 *   Additional options not specifically associated with the message.
 *
 * @deprecated To be removed before 8.x-1.0 release, use
 *   <code>sms_advanced_send()</code> instead.
 */
function _sms_advanced_process_send(SmsMessageInterface $sms, array $options = []) {
  return \Drupal::service('sms_provider.advanced')->send($sms, $options);
}

/**
 * Transparent cache for $sms being dispatched after queuing
 *
 * Need this so that other scripts can access the status as dispatch is ongoing
 * @param string $uuid
 * @return Array
 */
function &_sms_ui_get_cached($uuid) {
  if (!$cache = \Drupal::cache()->get('sms_ui_cache:' . $uuid)) {
    $cache = (object) array();
    // No cache found, so retrieve the data
    // then add to the cache with expiration after 1 day
    \Drupal::cache('cache')->set('sms_ui_cache:' . $uuid, $cache, time() + (60 * 60 * 24));
  }
  return $cache->data;
}

function _sms_ui_set_cached(&$sms) {
  \Drupal::cache('cache')->set('sms_ui_cache:' . $sms->uuid, $sms, time() + (60 * 60 * 24));
}
