sms_rule_based.settings:
  type: config_object
  label: Settings
  mapping:
    enable_rule_based_routing:
      type: boolean

sms_rule_based.ruleset.*:
  type: config_entity
  label: 'Rule-based Routing Ruleset'
  mapping:
    name:
      type: string
      label: "Ruleset name"
      description: "The machine name of the routing ruleset."
    label:
      type: label
      label: "Ruleset label"
      description: "The human-readable name of the routing ruleset."
    description:
      type: string
      label: "Ruleset description"
      description: "A description of what the routing ruleset does."
    weight:
      type: float
      label: "Ruleset weight"
      description: "The weight of this routing ruleset in the stack of rulesets."
    enabled:
      type: boolean
      label: "Enabled"
      description: 'Whether this ruleset is enabled to run or not.'
    rules:
      type: sequence
      label: 'Ruleset rules'
      description: 'The list of rules in this ruleset.'
      sequence:
        - type: sms_rule_based.ruleset_rule
          label: 'Ruleset rule'
    _ALL_TRUE_:
      type: boolean
      label: 'All conditions must be true'
      description: 'All conditions must be true for ruleset to apply.'
    gateway:
      type: string
      label: 'Gateway to route SMS'
      description: 'Gateway to route SMS satisfying this ruleset'

sms_rule_based.ruleset_rule:
  type: mapping
  label: 'Rule-based Routing Ruleset Rule'
  mapping:
    enabled:
      type: boolean
      label: 'Rule is enabled'
    operator:
      type: string
      label: 'Operator'
    operand:
      type: string
      label: 'Value to be compared on the right side of the operator'
    negated:
      type: boolean
      label: 'Negate the result if true'
